version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.11.4
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/proj

  test_go:
    docker:
      - image: circleci/golang:1.11.4
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run: go get github.com/jstemmer/go-junit-report
      - run: go get ./...

      - run:
          name: Go unit tests
          command: |
            trap "go-junit-report < ${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make go_test | tee ${TEST_RESULTS}/go-test.out

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  test:
    jobs:
      - checkout_code
      - test_go:
          requires:
            - checkout_code
